### ISSUE TITLE
Style suggestion

### ISSUE THREAD

**Issue by finnan444** [nikolaydubina/go-recipes#18]
as github offers copy icon by default it will be better to split command and output
![Screenshot from 2021-07-14 16-47-43](https://user-images.githubusercontent.com/28092100/125633617-2adfaa0f-4e08-4da4-abba-f01e2d3d4a04.png)

**It can be rewritten like this:**

> Use this when upgrading version of Go or finding old modules.

Run:
```bash
$ go list -deps -json ./... | jq -rc 'select(.Standard!=true and .Module.GoVersion!=null) | [.Module.GoVersion,.Module.Path] | join(" ")' | sort -V | uniq
```
Example output:
```bash
1.11 github.com/ugorji/go/codec
1.11 golang.org/x/crypto
1.12 github.com/golang/protobuf
...
```

**Comment by nikolaydubina** [comment]
Thanks, I noticed it too. But did not do it in order to: keep `$` at line beginning, which you can't run after copying whole string; keep single code block for shorter notation; keeping it visually similar to screenshot or [carbon](https://carbon.now.sh/).

Let's see if there are sufficiently many people who wants this change.

**Comment by nikolaydubina** [comment]
Switching to this style.
